[colors]
background = '#0a08138e'
black = '#0a0813'
blue = '#8b1d48'
cursor = '#c1c1c4'
cyan = '#504e7e'
foreground = '#c1c1c4'
green = '#8f3c85'
magenta = '#77517e'
red = '#516984'
tabs = '#c1c1c4'
tabs-active = '#89758a'
white = '#c1c1c4'
yellow = '#8e8c96'
dim-black = '#0a08138e'
dim-blue = '#8b1d488e'
dim-cyan = '#504e7e8e'
dim-foreground = '#c1c1c48e'
dim-green = '#8f3c858e'
dim-magenta = '#77517e8e'
dim-red = '#5169848e'
dim-white = '#89758a8e'
dim-yellow = '#8e8c968e'
light-black = '#BA2760'
light-blue = '#6B68A9'
light-cyan = '#BF50B2'
light-foreground = '#9F6CA9'
light-green = '#6C8CB1'
light-magenta = '#B79CB8'
light-red = '#c1c1c4'
light-white = '#BA2760'
light-yellow = '#6B68A9'
