# Shell variables
# Generated by 'wal'
wallpaper="/home/darkzin/Imagens/Wallpapers/wallhaven-8goj8k.jpg"

# Special
background='#0a0813'
foreground='#c1c1c4'
cursor='#c1c1c4'

# Colors
color0='#0a0813'
color1='#8b1d48'
color2='#504e7e'
color3='#8f3c85'
color4='#77517e'
color5='#516984'
color6='#89758a'
color7='#8e8c96'
color8='#5a576b'
color9='#BA2760'
color10='#6B68A9'
color11='#BF50B2'
color12='#9F6CA9'
color13='#6C8CB1'
color14='#B79CB8'
color15='#c1c1c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
