[colors.primary]
background = "#0a0813"
foreground = "#c1c1c4"

[colors.cursor]
text = "#0a0813"
cursor = "#c1c1c4"

[colors.vi_mode_cursor]
text = "#0a0813"
cursor = "#c1c1c4"

[colors.search.matches]
foreground = "#0a0813"
background = "#c1c1c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a576b"
background = "#8e8c96"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a0813"
red = "#8b1d48"
green = "#504e7e"
yellow = "#8f3c85"
blue = "#77517e"
magenta = "#516984"
cyan = "#89758a"
white = "#8e8c96"

[colors.bright]
black = "#5a576b"
red = "#BA2760"
green = "#6B68A9"
yellow = "#BF50B2"
blue = "#9F6CA9"
magenta = "#6C8CB1"
cyan = "#B79CB8"
white = "#c1c1c4"

[colors.dim]
black = "#c1c1c4"
red = "#BA2760"
green = "#6C8CB1"
yellow = "#BF50B2"
blue = "#9F6CA9"
magenta = "#6B68A9"
cyan = "#B79CB8"
white = "#5a576b"

