--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/darkzin/Imagens/Wallpapers/wallhaven-8goj8k.jpg"

-- Special
background="#0a0813"
foreground="#c1c1c4"
cursor="#c1c1c4"

-- Colors
color0="#0a0813"
color1="#8b1d48"
color2="#504e7e"
color3="#8f3c85"
color4="#77517e"
color5="#516984"
color6="#89758a"
color7="#8e8c96"
color8="#5a576b"
color9="#BA2760"
color10="#6B68A9"
color11="#BF50B2"
color12="#9F6CA9"
color13="#6C8CB1"
color14="#B79CB8"
color15="#c1c1c4"
